### PR TITLE
Secondary index support string

### PR DESCRIPTION
**Pull request by wuxiaobai24**
### What problem does this PR solve?

Secondary index support string type by hashing. 

Issue link:#1235

### Type of change

- [x] New Feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by yingfeng** [comment]
Thanks for your contribution!
Could you please add slt tests to this pr?   An example for secondary index could be seen here:
https://github.com/infiniflow/infinity/blob/main/test/sql/dql/index_scan/index_scan_date.slt

**Comment by wuxiaobai24** [comment]
> Thanks for your contribution! Could you please add slt tests to this pr? An example for secondary index could be seen here: https://github.com/infiniflow/infinity/blob/main/test/sql/dql/index_scan/index_scan_date.slt

ok, I've added slt test:
https://github.com/infiniflow/infinity/pull/1307/files#diff-f09a01a23fac82f5ff2da1689eadbdacb789fc3843874baae225a09dfd8df708

**Comment by yingfeng** [comment]
Your working branch is not clean, you could keep it consistent with upstream and submit pr again.

**Comment by wuxiaobai24** [comment]
> Your working branch is not clean, you could keep it consistent with upstream and submit pr again.

ok, It looks like I'm using a wrong way to merge the upstream code.

**Review by yangzq50 — APPROVED** [review]
Nice.

**Pull request merged**
